### ISSUE TITLE
esplink-tool.x64 is missing

### ISSUE THREAD

**Issue by fabaff** [wuxx/ESPLink#1]
The script tries to call [`esplink-tool.x64`](https://github.com/wuxx/ESPLink/blob/1be7c6544ed50abea63c94169778184084413285/tool/esplink-tool#L8) which is not available after cloning.

Could you please publish the source? People would then be able to compile it by themself. Thanks.

**Comment by wuxx** [comment]
ok

**Comment by wuxx** [comment]
already commit the `esplink-tool.x64` and the source code, please check

**Comment by fabaff** [comment]
Thank you

Was fixed with https://github.com/wuxx/ESPLink/commit/8adc83bc120e22e40a328c9e675caa79c0e56888
