### ISSUE TITLE
unable to find a matching CMSIS-DAP device

### ISSUE THREAD

**Issue by XiaoKaiRen** [wuxx/ESPLink#3]
### Environment
- OpenOCD :  v0.11.0-esp32-20220411
- Tool: ESPLink
- Operating System: Win10
### Problem Description
run ` openocd -f interface/cmsis-dap.cfg -f target/esp32s2.cfg`

Open On-Chip Debugger  v0.11.0-esp32-20220411 (2022-04-11-08:48)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: unable to find a matching CMSIS-DAP device

Assertion failed!

Program: C:\Users\James\.espressif\tools\openocd-esp32\v0.11.0-esp32-20220411\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 338

Expression: jtag_trst == 0

**Comment by wuxx** [comment]
try to add sudo in front of the command

**Comment by XiaoKaiRen** [comment]
I use WIN10 operating System  
try use system administrator also reminder unable to find a matching CMSIS-DAP device

**Comment by XiaoKaiRen** [comment]
> try to add sudo in front of the command

I use WIN10 operating System  
try use system administrator also reminder unable to find a matching CMSIS-DAP device


> try to add sudo in front of the command

**Comment by XiaoKaiRen** [comment]
> try to add sudo in front of the command

I use WIN10 operating System  
try use system administrator also reminder unable to find a matching CMSIS-DAP device
![擷取](https://user-images.githubusercontent.com/28284986/164972475-e5208878-f9dc-48ef-8f7a-9d076125c816.JPG)
this is the device administrator displayed

**Comment by wuxx** [comment]
try openocd 0.10.0 , not 0.11.0

**Comment by wuxx** [comment]
and can reference to the wiki
https://github.com/wuxx/ESPLink/wiki
