### ISSUE TITLE
./bootstrap 报错

### ISSUE THREAD

**Issue by lc168** [wuxx/ESPLink#4]
$git clone https://github.com/espressif/openocd-esp32.git （成功）
$cd openocd-esp32 （成功）
$./bootstrap  （报错）
fatal: unable to access ' server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
fatal: clone of ' into submodule path 'src/jtag/drivers/libjaylink' failed

**Comment by lc168** [comment]
具体打印：
~/esp/esp_openocd/openocd-esp32$ ./bootstrap 
+ aclocal --warnings=all
+ libtoolize --automake --copy
+ autoconf --warnings=all
+ autoheader --warnings=all
+ automake --warnings=all --gnu --add-missing --copy
configure.ac:24: installing './compile'
configure.ac:42: installing './config.guess'
configure.ac:42: installing './config.sub'
configure.ac:19: installing './install-sh'
configure.ac:19: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
Makefile.am:26: installing './mdate-sh'
Makefile.am:26: installing './texinfo.tex'
Setting up submodules
Submodule 'jimtcl' () registered for path 'jimtcl'
Submodule 'src/jtag/drivers/libjaylink' () registered for path 'src/jtag/drivers/libjaylink'
Submodule 'tools/git2cl' () registered for path 'tools/git2cl'
Cloning into 'jimtcl'...
remote: Enumerating objects: 8950, done.
remote: Counting objects: 100% (617/617), done.
remote: Compressing objects: 100% (271/271), done.
remote: Total 8950 (delta 361), reused 577 (delta 346), pack-reused 8333
Receiving objects: 100% (8950/8950), 15.32 MiB | 383.00 KiB/s, done.
Resolving deltas: 100% (5782/5782), done.
Checking connectivity... done.
Submodule path 'jimtcl': checked out 'a77ef1a6218fad4c928ddbdc03c1aedc41007e70'
Cloning into 'src/jtag/drivers/libjaylink'...
fatal: unable to access ' server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
fatal: clone of ' into submodule path 'src/jtag/drivers/libjaylink' failed

**Comment by lc168** [comment]
继续在终端输入：export GIT_SSL_NO_VERIFY=1（关闭认证以后）
执行 ./bootstrap报错
`+ aclocal --warnings=all
+ libtoolize --automake --copy
+ autoconf --warnings=all
+ autoheader --warnings=all
+ automake --warnings=all --gnu --add-missing --copy
src/jtag/drivers/Makefile.am:54: error: required directory ./src/jtag/drivers/libjaylink does not exist
Makefile.am:157:   'src/Makefile.am' included from here
src/Makefile.am:84:   'src/jtag/Makefile.am' included from here
src/jtag/Makefile.am:17:   'src/jtag/drivers/Makefile.am' included from here
src/jtag/drivers/Makefile.am:55: error: required directory ./src/jtag/drivers/libjaylink does not exist
Makefile.am:157:   'src/Makefile.am' included from here
src/Makefile.am:84:   'src/jtag/Makefile.am' included from here
src/jtag/Makefile.am:17:   'src/jtag/drivers/Makefile.am' included from here
lc@ubuntu:~/esp/esp_openocd/openocd-esp32$ `

**Comment by wuxx** [comment]
网络问题，同步仓库失败。
